setenv RUNNUM 1
setenv NRUNS 1
setenv SPLITNUM 0
setenv MINIRUNNUM -1
setenv CAM_DEBUG 0
setenv CAM_ALARM 1
setenv CAM_AGGREGATE 1
setenv CAM_POSTPAN 1
setenv CAM_OUTPUTDIR /adaqfs/home/apar/PREX/prompt/aggRootfiles/
setenv POSTPAN_ROOTFILES /chafs2/work1/apar/postpan-outputs/
