setenv RUNNUM 2362
setenv NRUNS 1
setenv SPLITNUM 0
setenv MINIRUNNUM -2
setenv CAM_DEBUG 6
setenv CAM_ALARM 1
setenv CAM_AGGREGATE 1
setenv CAM_POSTPAN 0
setenv POSTPAN_ROOTFILES /chafs2/work1/apar/postpan-outputs/
