#!/bin/tcsh

set FB_PROCESS = `ps -u apar -o pid,cmd | grep qwfeedback | grep -v grep | grep -v emacs | grep -v vim | head -1`
if ( "${FB_PROCESS}" != "" ) then
    echo "There is already another qwfeedback process running."
    echo "   Other process PID and command: ${FB_PROCESS}"
    exit
endif

source ~/PREX/setup_japan.tcsh

set MY_LOG_FILE = feedbacklog

if ( -f ${MY_LOG_FILE} ) then
   mv   ${MY_LOG_FILE}  `ls -lrt ${MY_LOG_FILE} -l --time-style +%y-%m-%d-%H:%M:%S | awk '{printf "%s_%s",$7,$6}'`
endif
./build/Feedback/qwfeedback --QwLog.logfile  ${MY_LOG_FILE} --config prex.conf --add-config qwfeedback.conf
    
