#!/bin/bash
# Author : Rakitha Beminiwattha
# 03/09/2011
# This bash script allows us to set the PC setpoints to get large positive charge asymmetry
# To use it,
# compile using 
# chmod +x SetLargePositive_A_q
# and then run ./SetLargePositive_A_q

# EPICS names PC [+] C1068_QDAC01PC [-] C1068_QDAC02

# Last time norminal values were updated
# Runs checked OUT - 10207 IN - 10198 - Rakitha 02/23/2011 - Old

#2. Runs checked OUT - 10810 IN - 10766 -Changed by Rakitha 03/17/2011 -Current
#PC_pos_t0_IN=43766
#PC_neg_t0_IN=40434
#PC_pos_t0_OUT=43000
#PC_neg_t0_OUT=41150

#3. Runs checked OUT - 10978 IN - 10969&10981 -Changed by Rakitha 03/30/2011 - rakithab@jlab.org
#PC_pos_t0_IN=42990
#PC_neg_t0_IN=41210
#PC_pos_t0_OUT=43238
#PC_neg_t0_OUT=40962

#4. Runs checked OUT - 11283 IN - 11286 -Changed by Rakitha 04/11/2011 - rakithab@jlab.org
#PC_pos_t0_IN=43300
#PC_neg_t0_IN=40899
#PC_pos_t0_OUT=42864 
#PC_neg_t0_OUT=41335

PC_Delta_Counts=2500

#5. No longer needs above values.
# Reads text files,
# /local/scratch/qweak/Last_good_PC_pos_OUT, 
# /local/scratch/qweak/Last_good_PC_neg_OUT
# /local/scratch/qweak/Last_good_PC_pos_IN
# /local/scratch/qweak/Last_good_PC_neg_IN
# set updated by the feedback program with last logged PC values.- Changed by Rakitha 04/15/2011 - rakithab@jlab.org


PC_pos_current="`caget -t C1068_QDAC01`"
PC_neg_current="`caget -t C1068_QDAC02`"


IHWP_State="`caget -t IGL1I00DI24_24M`"
#IHWP_State="IN"
echo "Offsetting Pockels Cell values by $PC_Delta_Counts"

if [ "$IHWP_State" == "OUT " ];then
#	PC_pos_t0_OUT="`cat /local/scratch/qweak/Last_good_PC_pos_OUT`"
#	PC_neg_t0_OUT="`cat /local/scratch/qweak/Last_good_PC_neg_OUT`"
        PC_pos_t0_OUT="`cat /local/scratch/qweak/norminal_PC_OUT`"
	PC_neg_t0_OUT="`cat /local/scratch/qweak/norminal_PC_OUT`"

    	echo "Current IHWP state is OUT"
	echo "Norminal PC_pos = $PC_pos_t0_OUT"
	echo "Current PC_pos = $PC_pos_current"
	echo "Norminal PC_neg = $PC_neg_t0_OUT"
	echo "Current PC_neg = $PC_neg_current"
	PC_pos_OUT=$(($PC_pos_t0_OUT + $PC_Delta_Counts))
	PC_neg_OUT=$(($PC_neg_t0_OUT - $PC_Delta_Counts))
	echo "Setting PC positive setpoint to $PC_pos_OUT to get large positive charge asymmetry"
	caput C1068_QDAC01 $PC_pos_OUT
	echo "Setting PC negative setpoint to $PC_neg_OUT to get large positive charge asymmetry"
	caput C1068_QDAC02 $PC_neg_OUT
else
#	PC_pos_t0_IN="`cat /local/scratch/qweak/Last_good_PC_pos_IN`"
#	PC_neg_t0_IN="`cat /local/scratch/qweak/Last_good_PC_neg_IN`"
        PC_pos_t0_IN="`cat /local/scratch/qweak/norminal_PC_IN`"
	PC_neg_t0_IN="`cat /local/scratch/qweak/norminal_PC_IN`"

    	echo "Current IHWP state is IN"	
	echo "Norminal PC_pos = $PC_pos_t0_IN"
	echo "Current PC_pos = $PC_pos_current"
	echo "Norminal PC_neg = $PC_neg_t0_IN"
	echo "Current PC_neg = $PC_neg_current"
	PC_pos_IN=$(($PC_pos_t0_IN + $PC_Delta_Counts))
	PC_neg_IN=$(($PC_neg_t0_IN - $PC_Delta_Counts))
	echo "Setting PC positive setpoint to $PC_pos_IN to get large positive charge asymmetry"
	#caput C1068_QDAC01 $PC_pos_IN
	echo "Setting PC negative setpoint to $PC_neg_IN to get large positive charge asymmetry"
	#caput C1068_QDAC02 $PC_neg_IN
fi


