void extract_corrections(TString avging = "crex_part", TString CutAna = "IncludeBMOD", TString suffix = "") {
  // 3 Parts
  //TString avging = "crex_part";
  // 6 IHWP * FLIP states
  //TString avging = "crex_slow_control";
  //TString suffix = "";
  
  // 3 Flip states
  //TString avging = "rcdb_flip_state";
  //TString suffix = "_wienwise";

  TChain * mini_reference_eigen_reg_5bpms_sorted_corrections_det_weighted   = new TChain("mini_reference_eigen_reg_5bpms_sorted_corrections_det_weighted");
  TChain * mini_reference_eigen_reg_allbpms_sorted_corrections_det_weighted = new TChain("mini_reference_eigen_reg_allbpms_sorted_corrections_det_weighted");
  TChain * mini_eigen_reg_5bpms_part_avg_corrections_det_weighted           = new TChain("mini_eigen_reg_5bpms_part_avg_corrections_det_weighted");
  TChain * mini_eigen_reg_allbpms_part_avg_corrections_det_weighted         = new TChain("mini_eigen_reg_allbpms_part_avg_corrections_det_weighted");
  TChain * mini_eigen_lagr_allbpms_part_avg_corrections_det_weighted        = new TChain("mini_eigen_lagr_allbpms_part_avg_corrections_det_weighted");
  TChain * mini_eigen_lagr_allbpms_part_avg_corrections_mon_weighted        = new TChain("mini_eigen_lagr_allbpms_part_avg_corrections_mon_weighted");
  TChain * mini_dit_part_avgd_corrections_det_weighted                      = new TChain("mini_dit_part_avgd_corrections_det_weighted");
  TChain * mini_regression_corrections_det_weighted                         = new TChain("mini_regression_corrections_det_weighted");
  TChain * mini_overload_corrections_det_weighted                           = new TChain("mini_overload_corrections_det_weighted");
  TChain * mini_dit_plain_corrections_det_weighted                          = new TChain("mini_dit_plain_corrections_det_weighted");
  TChain * mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted          = new TChain("mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted");
  TChain * mini_raw_det_asyms_det_weighted                                  = new TChain("mini_raw_det_asyms_det_weighted");
  TChain * mini_BCMs_det_weighted                                           = new TChain("mini_BCMs_det_weighted");
  TChain * mini_BPMs_det_weighted                                           = new TChain("mini_BPMs_det_weighted");
  TChain * mini_eigen_reg_allbpms_part_avg_monitors_det_weighted            = new TChain("mini_eigen_reg_allbpms_part_avg_monitors_det_weighted");
  TChain * mini_eigen_reg_5bpms_part_avg_monitors_det_weighted              = new TChain("mini_eigen_reg_5bpms_part_avg_monitors_det_weighted");
  TChain * mini_kinematics_det_weighted              = new TChain("mini_kinematics_det_weighted");


  mini_reference_eigen_reg_5bpms_sorted_corrections_det_weighted    -> Add("processed_respin2_data/results/CREX_All_"+CutAna+"_"+avging+"_Avg_Outputs"+suffix+"_main_det_corrections.root");
  mini_reference_eigen_reg_allbpms_sorted_corrections_det_weighted  -> Add("processed_respin2_data/results/CREX_All_"+CutAna+"_"+avging+"_Avg_Outputs"+suffix+"_main_det_corrections.root");
  mini_eigen_reg_5bpms_part_avg_corrections_det_weighted            -> Add("processed_respin2_data/results/CREX_All_"+CutAna+"_"+avging+"_Avg_Outputs"+suffix+"_main_det_corrections.root");
  mini_eigen_reg_allbpms_part_avg_corrections_det_weighted          -> Add("processed_respin2_data/results/CREX_All_"+CutAna+"_"+avging+"_Avg_Outputs"+suffix+"_main_det_corrections.root");
  mini_eigen_lagr_allbpms_part_avg_corrections_det_weighted         -> Add("processed_respin2_data/results/CREX_All_"+CutAna+"_"+avging+"_Avg_Outputs"+suffix+"_main_det_corrections.root");
  mini_eigen_lagr_allbpms_part_avg_corrections_mon_weighted         -> Add("processed_respin2_data/results/CREX_All_"+CutAna+"_"+avging+"_Avg_Outputs"+suffix+"_main_det_corrections.root");
  mini_dit_part_avgd_corrections_det_weighted                       -> Add("processed_respin2_data/results/CREX_All_"+CutAna+"_"+avging+"_Avg_Outputs"+suffix+"_main_det_corrections.root");
  mini_regression_corrections_det_weighted                          -> Add("processed_respin2_data/results/CREX_All_"+CutAna+"_"+avging+"_Avg_Outputs"+suffix+"_main_det_corrections.root");
  mini_overload_corrections_det_weighted                            -> Add("processed_respin2_data/results/CREX_All_"+CutAna+"_"+avging+"_Avg_Outputs"+suffix+"_main_det_corrections.root");
  mini_dit_plain_corrections_det_weighted                           -> Add("processed_respin2_data/results/CREX_All_"+CutAna+"_"+avging+"_Avg_Outputs"+suffix+"_main_det_corrections.root");
  mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted           -> Add("processed_respin2_data/results/CREX_All_"+CutAna+"_"+avging+"_Avg_Outputs"+suffix+"_main_det_corrections.root");
  mini_raw_det_asyms_det_weighted                                   -> Add("processed_respin2_data/results/CREX_All_"+CutAna+"_"+avging+"_Avg_Outputs"+suffix+"_main_det_corrections.root");
  mini_BCMs_det_weighted                                            -> Add("processed_respin2_data/results/CREX_All_"+CutAna+"_"+avging+"_Avg_Outputs"+suffix+"_main_det_corrections.root");
  mini_BPMs_det_weighted                                            -> Add("processed_respin2_data/results/CREX_All_"+CutAna+"_"+avging+"_Avg_Outputs"+suffix+"_main_det_corrections.root");
  mini_eigen_reg_allbpms_part_avg_monitors_det_weighted             -> Add("processed_respin2_data/results/CREX_All_"+CutAna+"_"+avging+"_Avg_Outputs"+suffix+"_main_det_corrections.root");
  mini_eigen_reg_5bpms_part_avg_monitors_det_weighted               -> Add("processed_respin2_data/results/CREX_All_"+CutAna+"_"+avging+"_Avg_Outputs"+suffix+"_main_det_corrections.root");
  mini_kinematics_det_weighted                                      -> Add("processed_respin2_data/results/CREX_All_"+CutAna+"_rcdb_slug_Avg_Outputs_kinematics_main_det_corrections.root");

  Printf("mini_reference_eigen_reg_5bpms_sorted_corrections_det_weighted,  manual_main_det_evMon0_mean/1e-9:manual_main_det_evMon1_mean/1e-9:manual_main_det_evMon2_mean/1e-9:manual_main_det_evMon3_mean/1e-9:manual_main_det_evMon4_mean/1e-9:manual_main_det_evMon5_mean/1e-9:manual_main_det_evMon6_mean/1e-9:manual_main_det_evMon7_mean/1e-9:manual_main_det_evMon8_mean/1e-9:manual_main_det_evMon9_mean/1e-9:manual_main_det_evMon10_mean/1e-9:manual_main_det_evMon11_mean/1e-9");
  mini_reference_eigen_reg_5bpms_sorted_corrections_det_weighted->Scan("manual_main_det_evMon0_mean/1e-9:manual_main_det_evMon1_mean/1e-9:manual_main_det_evMon2_mean/1e-9:manual_main_det_evMon3_mean/1e-9:manual_main_det_evMon4_mean/1e-9:manual_main_det_evMon5_mean/1e-9:manual_main_det_evMon6_mean/1e-9:manual_main_det_evMon7_mean/1e-9:manual_main_det_evMon8_mean/1e-9:manual_main_det_evMon9_mean/1e-9:manual_main_det_evMon10_mean/1e-9:manual_main_det_evMon11_mean/1e-9");

  Printf("mini_reference_eigen_reg_allbpms_sorted_corrections_det_weighted,  manual_main_det_evMon0_mean/1e-9:manual_main_det_evMon1_mean/1e-9:manual_main_det_evMon2_mean/1e-9:manual_main_det_evMon3_mean/1e-9:manual_main_det_evMon4_mean/1e-9:manual_main_det_evMon5_mean/1e-9:manual_main_det_evMon6_mean/1e-9:manual_main_det_evMon7_mean/1e-9:manual_main_det_evMon8_mean/1e-9:manual_main_det_evMon9_mean/1e-9:manual_main_det_evMon10_mean/1e-9:manual_main_det_evMon11_mean/1e-9");
  mini_reference_eigen_reg_allbpms_sorted_corrections_det_weighted->Scan("manual_main_det_evMon0_mean/1e-9:manual_main_det_evMon1_mean/1e-9:manual_main_det_evMon2_mean/1e-9:manual_main_det_evMon3_mean/1e-9:manual_main_det_evMon4_mean/1e-9:manual_main_det_evMon5_mean/1e-9:manual_main_det_evMon6_mean/1e-9:manual_main_det_evMon7_mean/1e-9:manual_main_det_evMon8_mean/1e-9:manual_main_det_evMon9_mean/1e-9:manual_main_det_evMon10_mean/1e-9:manual_main_det_evMon11_mean/1e-9");

  Printf("mini_eigen_reg_5bpms_part_avg_corrections_det_weighted,  manual_main_det_evMon0_new_mean/1e-9:manual_main_det_evMon1_new_mean/1e-9:manual_main_det_evMon2_new_mean/1e-9:manual_main_det_evMon3_new_mean/1e-9:manual_main_det_evMon4_new_mean/1e-9:manual_main_det_evMon5_new_mean/1e-9:manual_main_det_evMon6_new_mean/1e-9:manual_main_det_evMon7_new_mean/1e-9:manual_main_det_evMon8_new_mean/1e-9:manual_main_det_evMon9_new_mean/1e-9:manual_main_det_evMon10_new_mean/1e-9:manual_main_det_evMon11_new_mean/1e-9");
  mini_eigen_reg_5bpms_part_avg_corrections_det_weighted->Scan("manual_main_det_evMon0_new_mean/1e-9:manual_main_det_evMon1_new_mean/1e-9:manual_main_det_evMon2_new_mean/1e-9:manual_main_det_evMon3_new_mean/1e-9:manual_main_det_evMon4_new_mean/1e-9:manual_main_det_evMon5_new_mean/1e-9:manual_main_det_evMon6_new_mean/1e-9:manual_main_det_evMon7_new_mean/1e-9:manual_main_det_evMon8_new_mean/1e-9:manual_main_det_evMon9_new_mean/1e-9:manual_main_det_evMon10_new_mean/1e-9:manual_main_det_evMon11_new_mean/1e-9");

  Printf("mini_eigen_reg_allbpms_part_avg_corrections_det_weighted,  manual_main_det_evMon0_new_mean/1e-9:manual_main_det_evMon1_new_mean/1e-9:manual_main_det_evMon2_new_mean/1e-9:manual_main_det_evMon3_new_mean/1e-9:manual_main_det_evMon4_new_mean/1e-9:manual_main_det_evMon5_new_mean/1e-9:manual_main_det_evMon6_new_mean/1e-9:manual_main_det_evMon7_new_mean/1e-9:manual_main_det_evMon8_new_mean/1e-9:manual_main_det_evMon9_new_mean/1e-9:manual_main_det_evMon10_new_mean/1e-9:manual_main_det_evMon11_new_mean/1e-9");
  mini_eigen_reg_allbpms_part_avg_corrections_det_weighted->Scan("manual_main_det_evMon0_new_mean/1e-9:manual_main_det_evMon1_new_mean/1e-9:manual_main_det_evMon2_new_mean/1e-9:manual_main_det_evMon3_new_mean/1e-9:manual_main_det_evMon4_new_mean/1e-9:manual_main_det_evMon5_new_mean/1e-9:manual_main_det_evMon6_new_mean/1e-9:manual_main_det_evMon7_new_mean/1e-9:manual_main_det_evMon8_new_mean/1e-9:manual_main_det_evMon9_new_mean/1e-9:manual_main_det_evMon10_new_mean/1e-9:manual_main_det_evMon11_new_mean/1e-9");

  Printf("mini_eigen_lagr_allbpms_part_avg_corrections_det_weighted,  manual_main_det_evMon0_new_mean/1e-9:manual_main_det_evMon1_new_mean/1e-9:manual_main_det_evMon2_new_mean/1e-9:manual_main_det_evMon3_new_mean/1e-9:manual_main_det_evMon4_new_mean/1e-9:manual_main_det_evMon5_new_mean/1e-9:manual_main_det_evMon6_new_mean/1e-9:manual_main_det_evMon7_new_mean/1e-9:manual_main_det_evMon8_new_mean/1e-9:manual_main_det_evMon9_new_mean/1e-9:manual_main_det_evMon10_new_mean/1e-9:manual_main_det_evMon11_new_mean/1e-9:manual_main_det_evMon0_new_mean/1e-9+manual_main_det_evMon1_new_mean/1e-9+manual_main_det_evMon2_new_mean/1e-9+manual_main_det_evMon3_new_mean/1e-9+manual_main_det_evMon4_new_mean/1e-9+manual_main_det_evMon5_new_mean/1e-9+manual_main_det_evMon6_new_mean/1e-9+manual_main_det_evMon7_new_mean/1e-9+manual_main_det_evMon8_new_mean/1e-9+manual_main_det_evMon9_new_mean/1e-9+manual_main_det_evMon10_new_mean/1e-9+manual_main_det_evMon11_new_mean/1e-9:0.05*sqrt(pow(manual_main_det_evMon0_new_mean/1e-9,2)+pow(manual_main_det_evMon1_new_mean/1e-9,2)+pow(manual_main_det_evMon2_new_mean/1e-9,2)+pow(manual_main_det_evMon3_new_mean/1e-9,2)+pow(manual_main_det_evMon4_new_mean/1e-9,2)+pow(manual_main_det_evMon5_new_mean/1e-9,2)+pow(manual_main_det_evMon6_new_mean/1e-9,2)+pow(manual_main_det_evMon7_new_mean/1e-9,2)+pow(manual_main_det_evMon8_new_mean/1e-9,2)+pow(manual_main_det_evMon9_new_mean/1e-9,2)+pow(manual_main_det_evMon10_new_mean/1e-9,2)+pow(manual_main_det_evMon11_new_mean/1e-9,2))");
  mini_eigen_lagr_allbpms_part_avg_corrections_det_weighted->Scan("manual_main_det_evMon0_new_mean/1e-9:manual_main_det_evMon1_new_mean/1e-9:manual_main_det_evMon2_new_mean/1e-9:manual_main_det_evMon3_new_mean/1e-9:manual_main_det_evMon4_new_mean/1e-9:manual_main_det_evMon5_new_mean/1e-9:manual_main_det_evMon6_new_mean/1e-9:manual_main_det_evMon7_new_mean/1e-9:manual_main_det_evMon8_new_mean/1e-9:manual_main_det_evMon9_new_mean/1e-9:manual_main_det_evMon10_new_mean/1e-9:manual_main_det_evMon11_new_mean/1e-9:manual_main_det_evMon0_new_mean/1e-9+manual_main_det_evMon1_new_mean/1e-9+manual_main_det_evMon2_new_mean/1e-9+manual_main_det_evMon3_new_mean/1e-9+manual_main_det_evMon4_new_mean/1e-9+manual_main_det_evMon5_new_mean/1e-9+manual_main_det_evMon6_new_mean/1e-9+manual_main_det_evMon7_new_mean/1e-9+manual_main_det_evMon8_new_mean/1e-9+manual_main_det_evMon9_new_mean/1e-9+manual_main_det_evMon10_new_mean/1e-9+manual_main_det_evMon11_new_mean/1e-9:0.05*sqrt(pow(manual_main_det_evMon0_new_mean/1e-9,2)+pow(manual_main_det_evMon1_new_mean/1e-9,2)+pow(manual_main_det_evMon2_new_mean/1e-9,2)+pow(manual_main_det_evMon3_new_mean/1e-9,2)+pow(manual_main_det_evMon4_new_mean/1e-9,2)+pow(manual_main_det_evMon5_new_mean/1e-9,2)+pow(manual_main_det_evMon6_new_mean/1e-9,2)+pow(manual_main_det_evMon7_new_mean/1e-9,2)+pow(manual_main_det_evMon8_new_mean/1e-9,2)+pow(manual_main_det_evMon9_new_mean/1e-9,2)+pow(manual_main_det_evMon10_new_mean/1e-9,2)+pow(manual_main_det_evMon11_new_mean/1e-9,2))");

  Printf("mini_eigen_lagr_allbpms_part_avg_corrections_mon_weighted,  manual_main_det_evMon0_new_mean_err/1e-9:manual_main_det_evMon1_new_mean_err/1e-9:manual_main_det_evMon2_new_mean_err/1e-9:manual_main_det_evMon3_new_mean_err/1e-9:manual_main_det_evMon4_new_mean_err/1e-9:manual_main_det_evMon5_new_mean_err/1e-9:manual_main_det_evMon6_new_mean_err/1e-9:manual_main_det_evMon7_new_mean_err/1e-9:manual_main_det_evMon8_new_mean_err/1e-9:manual_main_det_evMon9_new_mean_err/1e-9:manual_main_det_evMon10_new_mean_err/1e-9:manual_main_det_evMon11_new_mean_err/1e-9:manual_main_det_evMon0_new_mean_err/1e-9+manual_main_det_evMon1_new_mean_err/1e-9+manual_main_det_evMon2_new_mean_err/1e-9+manual_main_det_evMon3_new_mean_err/1e-9+manual_main_det_evMon4_new_mean_err/1e-9+manual_main_det_evMon5_new_mean_err/1e-9+manual_main_det_evMon6_new_mean_err/1e-9+manual_main_det_evMon7_new_mean_err/1e-9+manual_main_det_evMon8_new_mean_err/1e-9+manual_main_det_evMon9_new_mean_err/1e-9+manual_main_det_evMon10_new_mean_err/1e-9+manual_main_det_evMon11_new_mean_err/1e-9:0.05*sqrt(pow(manual_main_det_evMon0_new_mean_err/1e-9,2)+pow(manual_main_det_evMon1_new_mean_err/1e-9,2)+pow(manual_main_det_evMon2_new_mean_err/1e-9,2)+pow(manual_main_det_evMon3_new_mean_err/1e-9,2)+pow(manual_main_det_evMon4_new_mean_err/1e-9,2)+pow(manual_main_det_evMon5_new_mean_err/1e-9,2)+pow(manual_main_det_evMon6_new_mean_err/1e-9,2)+pow(manual_main_det_evMon7_new_mean_err/1e-9,2)+pow(manual_main_det_evMon8_new_mean_err/1e-9,2)+pow(manual_main_det_evMon9_new_mean_err/1e-9,2)+pow(manual_main_det_evMon10_new_mean_err/1e-9,2)+pow(manual_main_det_evMon11_new_mean_err/1e-9,2))");
  mini_eigen_lagr_allbpms_part_avg_corrections_mon_weighted->Scan("manual_main_det_evMon0_new_mean_err/1e-9:manual_main_det_evMon1_new_mean_err/1e-9:manual_main_det_evMon2_new_mean_err/1e-9:manual_main_det_evMon3_new_mean_err/1e-9:manual_main_det_evMon4_new_mean_err/1e-9:manual_main_det_evMon5_new_mean_err/1e-9:manual_main_det_evMon6_new_mean_err/1e-9:manual_main_det_evMon7_new_mean_err/1e-9:manual_main_det_evMon8_new_mean_err/1e-9:manual_main_det_evMon9_new_mean_err/1e-9:manual_main_det_evMon10_new_mean_err/1e-9:manual_main_det_evMon11_new_mean_err/1e-9:manual_main_det_evMon0_new_mean_err/1e-9+manual_main_det_evMon1_new_mean_err/1e-9+manual_main_det_evMon2_new_mean_err/1e-9+manual_main_det_evMon3_new_mean_err/1e-9+manual_main_det_evMon4_new_mean_err/1e-9+manual_main_det_evMon5_new_mean_err/1e-9+manual_main_det_evMon6_new_mean_err/1e-9+manual_main_det_evMon7_new_mean_err/1e-9+manual_main_det_evMon8_new_mean_err/1e-9+manual_main_det_evMon9_new_mean_err/1e-9+manual_main_det_evMon10_new_mean_err/1e-9+manual_main_det_evMon11_new_mean_err/1e-9:0.05*sqrt(pow(manual_main_det_evMon0_new_mean_err/1e-9,2)+pow(manual_main_det_evMon1_new_mean_err/1e-9,2)+pow(manual_main_det_evMon2_new_mean_err/1e-9,2)+pow(manual_main_det_evMon3_new_mean_err/1e-9,2)+pow(manual_main_det_evMon4_new_mean_err/1e-9,2)+pow(manual_main_det_evMon5_new_mean_err/1e-9,2)+pow(manual_main_det_evMon6_new_mean_err/1e-9,2)+pow(manual_main_det_evMon7_new_mean_err/1e-9,2)+pow(manual_main_det_evMon8_new_mean_err/1e-9,2)+pow(manual_main_det_evMon9_new_mean_err/1e-9,2)+pow(manual_main_det_evMon10_new_mean_err/1e-9,2)+pow(manual_main_det_evMon11_new_mean_err/1e-9,2))");

  Printf("mini_eigen_lagr_allbpms_part_avg_corrections_det_weighted,  us_dd_evMon0_new_mean/1e-9:us_dd_evMon1_new_mean/1e-9:us_dd_evMon2_new_mean/1e-9:us_dd_evMon3_new_mean/1e-9:us_dd_evMon4_new_mean/1e-9:us_dd_evMon5_new_mean/1e-9:us_dd_evMon6_new_mean/1e-9:us_dd_evMon7_new_mean/1e-9:us_dd_evMon8_new_mean/1e-9:us_dd_evMon9_new_mean/1e-9:us_dd_evMon10_new_mean/1e-9:us_dd_evMon11_new_mean/1e-9:us_dd_evMon0_new_mean/1e-9+us_dd_evMon1_new_mean/1e-9+us_dd_evMon2_new_mean/1e-9+us_dd_evMon3_new_mean/1e-9+us_dd_evMon4_new_mean/1e-9+us_dd_evMon5_new_mean/1e-9+us_dd_evMon6_new_mean/1e-9+us_dd_evMon7_new_mean/1e-9+us_dd_evMon8_new_mean/1e-9+us_dd_evMon9_new_mean/1e-9+us_dd_evMon10_new_mean/1e-9+us_dd_evMon11_new_mean/1e-9:0.05*sqrt(pow(us_dd_evMon0_new_mean/1e-9,2)+pow(us_dd_evMon1_new_mean/1e-9,2)+pow(us_dd_evMon2_new_mean/1e-9,2)+pow(us_dd_evMon3_new_mean/1e-9,2)+pow(us_dd_evMon4_new_mean/1e-9,2)+pow(us_dd_evMon5_new_mean/1e-9,2)+pow(us_dd_evMon6_new_mean/1e-9,2)+pow(us_dd_evMon7_new_mean/1e-9,2)+pow(us_dd_evMon8_new_mean/1e-9,2)+pow(us_dd_evMon9_new_mean/1e-9,2)+pow(us_dd_evMon10_new_mean/1e-9,2)+pow(us_dd_evMon11_new_mean/1e-9,2))");
  mini_eigen_lagr_allbpms_part_avg_corrections_det_weighted->Scan("us_dd_evMon0_new_mean/1e-9:us_dd_evMon1_new_mean/1e-9:us_dd_evMon2_new_mean/1e-9:us_dd_evMon3_new_mean/1e-9:us_dd_evMon4_new_mean/1e-9:us_dd_evMon5_new_mean/1e-9:us_dd_evMon6_new_mean/1e-9:us_dd_evMon7_new_mean/1e-9:us_dd_evMon8_new_mean/1e-9:us_dd_evMon9_new_mean/1e-9:us_dd_evMon10_new_mean/1e-9:us_dd_evMon11_new_mean/1e-9:us_dd_evMon0_new_mean/1e-9+us_dd_evMon1_new_mean/1e-9+us_dd_evMon2_new_mean/1e-9+us_dd_evMon3_new_mean/1e-9+us_dd_evMon4_new_mean/1e-9+us_dd_evMon5_new_mean/1e-9+us_dd_evMon6_new_mean/1e-9+us_dd_evMon7_new_mean/1e-9+us_dd_evMon8_new_mean/1e-9+us_dd_evMon9_new_mean/1e-9+us_dd_evMon10_new_mean/1e-9+us_dd_evMon11_new_mean/1e-9:0.05*sqrt(pow(us_dd_evMon0_new_mean/1e-9,2)+pow(us_dd_evMon1_new_mean/1e-9,2)+pow(us_dd_evMon2_new_mean/1e-9,2)+pow(us_dd_evMon3_new_mean/1e-9,2)+pow(us_dd_evMon4_new_mean/1e-9,2)+pow(us_dd_evMon5_new_mean/1e-9,2)+pow(us_dd_evMon6_new_mean/1e-9,2)+pow(us_dd_evMon7_new_mean/1e-9,2)+pow(us_dd_evMon8_new_mean/1e-9,2)+pow(us_dd_evMon9_new_mean/1e-9,2)+pow(us_dd_evMon10_new_mean/1e-9,2)+pow(us_dd_evMon11_new_mean/1e-9,2))");

  Printf("mini_eigen_lagr_allbpms_part_avg_corrections_mon_weighted,  us_dd_evMon0_new_mean_err/1e-9:us_dd_evMon1_new_mean_err/1e-9:us_dd_evMon2_new_mean_err/1e-9:us_dd_evMon3_new_mean_err/1e-9:us_dd_evMon4_new_mean_err/1e-9:us_dd_evMon5_new_mean_err/1e-9:us_dd_evMon6_new_mean_err/1e-9:us_dd_evMon7_new_mean_err/1e-9:us_dd_evMon8_new_mean_err/1e-9:us_dd_evMon9_new_mean_err/1e-9:us_dd_evMon10_new_mean_err/1e-9:us_dd_evMon11_new_mean_err/1e-9:us_dd_evMon0_new_mean_err/1e-9+us_dd_evMon1_new_mean_err/1e-9+us_dd_evMon2_new_mean_err/1e-9+us_dd_evMon3_new_mean_err/1e-9+us_dd_evMon4_new_mean_err/1e-9+us_dd_evMon5_new_mean_err/1e-9+us_dd_evMon6_new_mean_err/1e-9+us_dd_evMon7_new_mean_err/1e-9+us_dd_evMon8_new_mean_err/1e-9+us_dd_evMon9_new_mean_err/1e-9+us_dd_evMon10_new_mean_err/1e-9+us_dd_evMon11_new_mean_err/1e-9:0.05*sqrt(pow(us_dd_evMon0_new_mean_err/1e-9,2)+pow(us_dd_evMon1_new_mean_err/1e-9,2)+pow(us_dd_evMon2_new_mean_err/1e-9,2)+pow(us_dd_evMon3_new_mean_err/1e-9,2)+pow(us_dd_evMon4_new_mean_err/1e-9,2)+pow(us_dd_evMon5_new_mean_err/1e-9,2)+pow(us_dd_evMon6_new_mean_err/1e-9,2)+pow(us_dd_evMon7_new_mean_err/1e-9,2)+pow(us_dd_evMon8_new_mean_err/1e-9,2)+pow(us_dd_evMon9_new_mean_err/1e-9,2)+pow(us_dd_evMon10_new_mean_err/1e-9,2)+pow(us_dd_evMon11_new_mean_err/1e-9,2))");
  mini_eigen_lagr_allbpms_part_avg_corrections_mon_weighted->Scan("us_dd_evMon0_new_mean_err/1e-9:us_dd_evMon1_new_mean_err/1e-9:us_dd_evMon2_new_mean_err/1e-9:us_dd_evMon3_new_mean_err/1e-9:us_dd_evMon4_new_mean_err/1e-9:us_dd_evMon5_new_mean_err/1e-9:us_dd_evMon6_new_mean_err/1e-9:us_dd_evMon7_new_mean_err/1e-9:us_dd_evMon8_new_mean_err/1e-9:us_dd_evMon9_new_mean_err/1e-9:us_dd_evMon10_new_mean_err/1e-9:us_dd_evMon11_new_mean_err/1e-9:us_dd_evMon0_new_mean_err/1e-9+us_dd_evMon1_new_mean_err/1e-9+us_dd_evMon2_new_mean_err/1e-9+us_dd_evMon3_new_mean_err/1e-9+us_dd_evMon4_new_mean_err/1e-9+us_dd_evMon5_new_mean_err/1e-9+us_dd_evMon6_new_mean_err/1e-9+us_dd_evMon7_new_mean_err/1e-9+us_dd_evMon8_new_mean_err/1e-9+us_dd_evMon9_new_mean_err/1e-9+us_dd_evMon10_new_mean_err/1e-9+us_dd_evMon11_new_mean_err/1e-9:0.05*sqrt(pow(us_dd_evMon0_new_mean_err/1e-9,2)+pow(us_dd_evMon1_new_mean_err/1e-9,2)+pow(us_dd_evMon2_new_mean_err/1e-9,2)+pow(us_dd_evMon3_new_mean_err/1e-9,2)+pow(us_dd_evMon4_new_mean_err/1e-9,2)+pow(us_dd_evMon5_new_mean_err/1e-9,2)+pow(us_dd_evMon6_new_mean_err/1e-9,2)+pow(us_dd_evMon7_new_mean_err/1e-9,2)+pow(us_dd_evMon8_new_mean_err/1e-9,2)+pow(us_dd_evMon9_new_mean_err/1e-9,2)+pow(us_dd_evMon10_new_mean_err/1e-9,2)+pow(us_dd_evMon11_new_mean_err/1e-9,2))");

  Printf("mini_dit_part_avgd_corrections_det_weighted,  manual_main_det_evMon0_mean/1e-6:manual_main_det_evMon1_mean/1e-6:manual_main_det_evMon2_mean/1e-6:manual_main_det_evMon3_mean/1e-6:manual_main_det_evMon4_mean/1e-6:manual_main_det_evMon5_mean/1e-9:manual_main_det_evMon6_mean/1e-9:manual_main_det_evMon7_mean/1e-9:manual_main_det_evMon8_mean/1e-9:manual_main_det_evMon9_mean/1e-9:manual_main_det_evMon10_mean/1e-9:manual_main_det_evMon11_mean/1e-9");
  mini_dit_part_avgd_corrections_det_weighted->Scan("manual_main_det_evMon0_mean/1e-6:manual_main_det_evMon1_mean/1e-6:manual_main_det_evMon2_mean/1e-6:manual_main_det_evMon3_mean/1e-6:manual_main_det_evMon4_mean/1e-6:manual_main_det_evMon5_mean/1e-9:manual_main_det_evMon6_mean/1e-9:manual_main_det_evMon7_mean/1e-9:manual_main_det_evMon8_mean/1e-9:manual_main_det_evMon9_mean/1e-9:manual_main_det_evMon10_mean/1e-9:manual_main_det_evMon11_mean/1e-9");

  Printf("mini_regression_corrections_det_weighted,  manual_main_det_bpm12X_mean/1e-9:manual_main_det_bpm4eX_mean/1e-9:manual_main_det_bpm1X_mean/1e-9:manual_main_det_bpm4aY_mean/1e-9:manual_main_det_bpm4eY_mean/1e-9:manual_main_det_bpm11X_mean/1e-9:manual_main_det_bpm4aX_mean/1e-9:manual_main_det_bpm11Y_mean/1e-9:manual_main_det_bpm16X_mean/1e-9:manual_main_det_bpm16Y_mean/1e-9:manual_main_det_bpm12Y_mean/1e-9:manual_main_det_bpm1Y_mean/1e-9");
  mini_regression_corrections_det_weighted->Scan("manual_main_det_bpm12X_mean/1e-9:manual_main_det_bpm4eX_mean/1e-9:manual_main_det_bpm1X_mean/1e-9:manual_main_det_bpm4aY_mean/1e-9:manual_main_det_bpm4eY_mean/1e-9:manual_main_det_bpm11X_mean/1e-9:manual_main_det_bpm4aX_mean/1e-9:manual_main_det_bpm11Y_mean/1e-9:manual_main_det_bpm16X_mean/1e-9:manual_main_det_bpm16Y_mean/1e-9:manual_main_det_bpm12Y_mean/1e-9:manual_main_det_bpm1Y_mean/1e-9");

  Printf("mini_overload_corrections_det_weighted,  manual_main_det_bpm12X_mean/1e-9:manual_main_det_bpm4eX_mean/1e-9:manual_main_det_bpm1X_mean/1e-9:manual_main_det_bpm4aY_mean/1e-9:manual_main_det_bpm4eY_mean/1e-9:manual_main_det_bpm11X_mean/1e-9:manual_main_det_bpm4aX_mean/1e-9:manual_main_det_bpm11Y_mean/1e-9:manual_main_det_bpm16X_mean/1e-9:manual_main_det_bpm16Y_mean/1e-9:manual_main_det_bpm12Y_mean/1e-9:manual_main_det_bpm1Y_mean/1e-9");
  mini_overload_corrections_det_weighted->Scan("manual_main_det_bpm12X_mean/1e-9:manual_main_det_bpm4eX_mean/1e-9:manual_main_det_bpm1X_mean/1e-9:manual_main_det_bpm4aY_mean/1e-9:manual_main_det_bpm4eY_mean/1e-9:manual_main_det_bpm11X_mean/1e-9:manual_main_det_bpm4aX_mean/1e-9:manual_main_det_bpm11Y_mean/1e-9:manual_main_det_bpm16X_mean/1e-9:manual_main_det_bpm16Y_mean/1e-9:manual_main_det_bpm12Y_mean/1e-9:manual_main_det_bpm1Y_mean/1e-9");

  Printf("mini_dit_plain_corrections_det_weighted,  manual_main_det_12X_mean/1e-6:manual_main_det_4eX_mean/1e-6:manual_main_det_1X_mean/1e-6:manual_main_det_4aY_mean/1e-6:manual_main_det_4eY_mean/1e-6:manual_main_det_11X_mean/1e-6:manual_main_det_4aX_mean/1e-6:manual_main_det_11Y_mean/1e-6:manual_main_det_16X_mean/1e-6:manual_main_det_16Y_mean/1e-6:manual_main_det_12Y_mean/1e-6:manual_main_det_1Y_mean/1e-6");
  mini_dit_plain_corrections_det_weighted->Scan("manual_main_det_12X_mean/1e-6:manual_main_det_4eX_mean/1e-6:manual_main_det_1X_mean/1e-6:manual_main_det_4aY_mean/1e-6:manual_main_det_4eY_mean/1e-6:manual_main_det_11X_mean/1e-6:manual_main_det_4aX_mean/1e-6:manual_main_det_11Y_mean/1e-6:manual_main_det_16X_mean/1e-6:manual_main_det_16Y_mean/1e-6:manual_main_det_12Y_mean/1e-6:manual_main_det_1Y_mean/1e-6");

  Printf("mini_BCMs_det_weighted,  asym_bcm_an_diff_mean/1e-9:asym_bcm_an_diff_mean_err/1e-9");
  mini_BCMs_det_weighted->Scan("asym_bcm_an_diff_nentries:asym_bcm_an_diff_mean/1e-9:asym_bcm_an_diff_mean_err/1e-9");

  Printf("mini_BCMs_det_weighted,  asym_bcm_target_mean/1e-9:asym_bcm_target_mean_err/1e-9");
  mini_BCMs_det_weighted->Scan("asym_bcm_target_mean_nentries:asym_bcm_target_mean/1e-9:asym_bcm_target_mean_err/1e-9");

  Printf("mini_BPMs_det_weighted,  diff_bpm4aX_mean/1e-6:diff_bpm4aY_mean/1e-6:diff_bpm4eX_mean/1e-6:diff_bpm4eY_mean/1e-6:diff_bpm1X_mean/1e-6:diff_bpm1Y_mean/1e-6:diff_bpm16X_mean/1e-6:diff_bpm16Y_mean/1e-6:diff_bpm11X_mean/1e-6:diff_bpm11Y_mean/1e-6:diff_bpm12X_mean/1e-6:diff_bpm12Y_mean/1e-6");
  mini_BPMs_det_weighted->Scan("diff_bpm4aX_mean/1e-6:diff_bpm4aY_mean/1e-6:diff_bpm4eX_mean/1e-6:diff_bpm4eY_mean/1e-6:diff_bpm1X_mean/1e-6:diff_bpm1Y_mean/1e-6:diff_bpm16X_mean/1e-6:diff_bpm16Y_mean/1e-6:diff_bpm11X_mean/1e-6:diff_bpm11Y_mean/1e-6:diff_bpm12X_mean/1e-6:diff_bpm12Y_mean/1e-6");

  Printf("mini_BPMs_det_weighted,  diff_bpm4aX_mean_err/1e-6:diff_bpm4aY_mean_err/1e-6:diff_bpm4eX_mean_err/1e-6:diff_bpm4eY_mean_err/1e-6:diff_bpm1X_mean_err/1e-6:diff_bpm1Y_mean_err/1e-6:diff_bpm16X_mean_err/1e-6:diff_bpm16Y_mean_err/1e-6:diff_bpm11X_mean_err/1e-6:diff_bpm11Y_mean_err/1e-6:diff_bpm12X_mean_err/1e-6:diff_bpm12Y_mean_err/1e-6");
  mini_BPMs_det_weighted->Scan("diff_bpm4aX_mean_err/1e-6:diff_bpm4aY_mean_err/1e-6:diff_bpm4eX_mean_err/1e-6:diff_bpm4eY_mean_err/1e-6:diff_bpm1X_mean_err/1e-6:diff_bpm1Y_mean_err/1e-6:diff_bpm16X_mean_err/1e-6:diff_bpm16Y_mean_err/1e-6:diff_bpm11X_mean_err/1e-6:diff_bpm11Y_mean_err/1e-6:diff_bpm12X_mean_err/1e-6:diff_bpm12Y_mean_err/1e-6");

  Printf("mini_eigen_reg_allbpms_part_avg_monitors_det_weighted,  diff_evMon0_mean/1e-6:diff_evMon1_mean/1e-6:diff_evMon2_mean/1e-6:diff_evMon3_mean/1e-6:diff_evMon4_mean/1e-6:diff_evMon5_mean/1e-6:diff_evMon6_mean/1e-6:diff_evMon7_mean/1e-6:diff_evMon8_mean/1e-6:diff_evMon9_mean/1e-6:diff_evMon10_mean/1e-6:diff_evMon11_mean/1e-6");
  mini_eigen_reg_allbpms_part_avg_monitors_det_weighted->Scan("diff_evMon0_mean/1e-6:diff_evMon1_mean/1e-6:diff_evMon2_mean/1e-6:diff_evMon3_mean/1e-6:diff_evMon4_mean/1e-6:diff_evMon5_mean/1e-6:diff_evMon6_mean/1e-6:diff_evMon7_mean/1e-6:diff_evMon8_mean/1e-6:diff_evMon9_mean/1e-6:diff_evMon10_mean/1e-6:diff_evMon11_mean/1e-6");

  Printf("mini_eigen_reg_allbpms_part_avg_monitors_det_weighted,  diff_evMon0_mean_err/1e-6:diff_evMon1_mean_err/1e-6:diff_evMon2_mean_err/1e-6:diff_evMon3_mean_err/1e-6:diff_evMon4_mean_err/1e-6:diff_evMon5_mean_err/1e-6:diff_evMon6_mean_err/1e-6:diff_evMon7_mean_err/1e-6:diff_evMon8_mean_err/1e-6:diff_evMon9_mean_err/1e-6:diff_evMon10_mean_err/1e-6:diff_evMon11_mean_err/1e-6");
  mini_eigen_reg_allbpms_part_avg_monitors_det_weighted->Scan("diff_evMon0_mean_err/1e-6:diff_evMon1_mean_err/1e-6:diff_evMon2_mean_err/1e-6:diff_evMon3_mean_err/1e-6:diff_evMon4_mean_err/1e-6:diff_evMon5_mean_err/1e-6:diff_evMon6_mean_err/1e-6:diff_evMon7_mean_err/1e-6:diff_evMon8_mean_err/1e-6:diff_evMon9_mean_err/1e-6:diff_evMon10_mean_err/1e-6:diff_evMon11_mean_err/1e-6");

  Printf("mini_eigen_reg_5bpms_part_avg_monitors_det_weighted,  diff_evMon0_mean/1e-6:diff_evMon1_mean/1e-6:diff_evMon2_mean/1e-6:diff_evMon3_mean/1e-6:diff_evMon4_mean/1e-6");
  mini_eigen_reg_5bpms_part_avg_monitors_det_weighted->Scan("diff_evMon0_mean/1e-6:diff_evMon1_mean/1e-6:diff_evMon2_mean/1e-6:diff_evMon3_mean/1e-6:diff_evMon4_mean/1e-6");

  //Printf("mini_kinematics_det_weighted, _"+CutAna+"_diff_targ_positionX_mean/1e-6,_"+CutAna+"_diff_targ_positionY_mean/1e-6,_"+CutAna+"_diff_targ_thetaX_mean/1e-6,_"+CutAna+"_diff_targ_thetaY_mean/1e-6,_"+CutAna+"_diff_dispE_bpm12X/1");
  //mini_kinematics_det_weighted->Scan("_"+CutAna+"_diff_targ_positionX_mean/1e-6;_"+CutAna+"_diff_targ_positionY_mean/1e-6;_"+CutAna+"_diff_targ_thetaX_mean/1e-6;_"+CutAna+"_diff_targ_thetaY_mean/1e-6;_"+CutAna+"_diff_dispE_bpm12X/1");


  Printf("mini_raw_det_asyms_det_weighted,  asym_manual_main_det_mean/1e-9:asym_manual_main_det_mean_err/1e-9:asym_manual_main_det_mean_err_global/1e-9");
  mini_raw_det_asyms_det_weighted->Scan("asym_manual_main_det_mean_nentries:asym_manual_main_det_mean/1e-9:asym_manual_main_det_mean_err/1e-9:asym_manual_main_det_mean_err_global/1e-9");

  Printf("mini_raw_det_asyms_det_weighted,  asym_manual_main_det_mean/1e-9:asym_manual_main_det_mean_err/1e-9:asym_manual_main_det_mean_self/1e-9:asym_manual_main_det_mean_err_global/1e-9:asym_manual_main_det_mean_self_err/1e-9");
  mini_raw_det_asyms_det_weighted->Scan("asym_manual_main_det_mean_nentries:asym_manual_main_det_mean/1e-9:asym_manual_main_det_mean_err/1e-9:asym_manual_main_det_mean_self/1e-9:asym_manual_main_det_mean_err_global/1e-9:asym_manual_main_det_mean_self_err/1e-9");

  Printf("mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted,  eigen_lagr_asym_manual_main_det_mean/1e-9:eigen_lagr_asym_manual_main_det_mean_err/1e-9:weight (1/err^2 / sum weights)");
  mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->Scan("eigen_lagr_asym_manual_main_det_mean_nentries:eigen_lagr_asym_manual_main_det_mean/1e-9:eigen_lagr_asym_manual_main_det_mean_err/1e-9:pow(eigen_lagr_asym_manual_main_det_mean_err/1e-9,-2)/pow(85.76,-2):eigen_lagr_asym_manual_main_det_mean_chi2:eigen_lagr_asym_manual_main_det_mean_nentries");

  Printf("mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted,  eigen_lagr_asym_us_dd_det_mean/1e-9:eigen_lagr_asym_us_dd_det_mean_err/1e-9");
  mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->Scan("eigen_lagr_asym_us_dd_mean_nentries:eigen_lagr_asym_us_dd_mean/1e-9:eigen_lagr_asym_us_dd_mean_err/1e-9");
}
