TFile *_file0 = TFile::Open("processed_respin2_data/results/CREX_All_ErrorFlag_rcdb_slug_Avg_Outputs_main_det_corrections.root")
.ls
mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->Scan()
mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->Draw("eigen_lagr_asym_manual_main_det_mean:eigen_lagr_asym_manual_main_det_mean_err","rcdb_flip_state<=2")
mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->Draw("eigen_lagr_asym_manual_main_det_mean/1e-9:eigen_lagr_asym_manual_main_det_mean_err/1e-9:rcdb_slug","rcdb_flip_state<=2")
mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->Draw("eigen_lagr_asym_manual_main_det_mean/1e-9:eigen_lagr_asym_manual_main_det_mean_err/1e-9:rcdb_slug","rcdb_flip_state<=2","goff")
mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->Draw("eigen_lagr_asym_manual_main_det_mean/1e-9:eigen_lagr_asym_manual_main_det_mean_err/1e-9:rcdb_slug","rcdb_flip_state<=2 && rcdb_flip_state == 1 && rcdb_ihwp == 1","goff")
TGraphErrors * tge_IN_RIGHT = new TGraphErrors(34,mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->GetV3(),mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->GetV1(),0,mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->GetV2())
tge_IN_RIGHT->SetMarkerStyle(22)
tge_IN_RIGHT->SetMarkerColor(3)
TMultiGraph * mg = new TMultiGraph()
mg->Add(tge_IN_RIGHT)
mg->Draw()
mg->Draw("ape")
mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->Draw("eigen_lagr_asym_manual_main_det_mean/1e-9:eigen_lagr_asym_manual_main_det_mean_err/1e-9:rcdb_slug","rcdb_flip_state<=2 && rcdb_flip_state == 1 && rcdb_ihwp == 2","goff")
TGraphErrors * tge_OUT_RIGHT = new TGraphErrors(39,mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->GetV3(),mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->GetV1(),0,mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->GetV2())
tge_IN_RIGHT->SetMarkerColor(2)
tge_IN_RIGHT->SetMarkerColor(3)
tge_OUT_RIGHT->SetMarkerColor(3)
tge_OUT_RIGHT->SetMarkerStyle(23)
mg->Add(tge_OUT_RIGHT)
mg->Draw("ape")
tge_OUT_RIGHT->SetMarkerColor(2)
c1->Clear()
mg->Draw("ape")
mg->SetRangeUser(-3000,3000)
mg->SetMinimum(-3000)
mg->SetMaximum(3000)
mg->Draw("ape")
mg->SetMaximum(5000)
mg->SetMinimum(-5000)
mg->Draw("ape")
mg->SetMinimum(-8000)
mg->SetMaximum(8000)
mg->Draw("ape")
mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->Draw("eigen_lagr_asym_manual_main_det_mean/1e-9:eigen_lagr_asym_manual_main_det_mean_err/1e-9:rcdb_slug","rcdb_flip_state<=2 && rcdb_flip_state == 2 && rcdb_ihwp == 1","goff")
TGraphErrors * tge_IN_LEFT = new TGraphErrors(23,mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->GetV3(),mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->GetV1(),0,mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->GetV2())
tge_IN_LEFT->SetMarkerColor(6)
tge_IN_LEFT->SetMarkerStyle(23)
mg->Add(tge_IN_LEFT)
mg->Draw("ape")
mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->Draw("eigen_lagr_asym_manual_main_det_mean/1e-9:eigen_lagr_asym_manual_main_det_mean_err/1e-9:rcdb_slug","rcdb_flip_state<=2 && rcdb_flip_state == 2 && rcdb_ihwp == 2","goff")
TGraphErrors * tge_OUT_LEFT = new TGraphErrors(25,mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->GetV3(),mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->GetV1(),0,mini_eigen_lagr_allbpms_part_avg_det_asyms_det_weighted->GetV2())
tge_IN_LEFT->SetMarkerColor(4)
tge_OUT_LEFT->SetMarkerStyle(22)
tge_IN_LEFT->SetMarkerColor(6)
tge_OUT_LEFT->SetMarkerColor(4)
mg->Add(tge_OUT_LEFT)
mg->Draw("ape")
mg->SetMaximum(6000)
mg->SetMaximum(8000)
mg->SetMaximum(8500)
mg->SetMinimum(-8500)
mg->Draw("ape")
mg->SetNameTitle("Asymmetry vs. Slug","12BPM Lagrange Main detector Asymmetry vs. Slug;Slug;Asymmetry (ppb)")
mg->Draw("ape")
mg->GetHistogram()->SetNameTitle("Asymmetry vs. Slug","12BPM Lagrange Main detector Asymmetry vs. Slug;Slug;Asymmetry (ppb)")
c1->SaveAs("noleg_maindet_asym.pdf")
TLegend *leg = new TLegend(0.1, 0.7, 0.3, 0.9);
leg->SetFillColor(0)
leg->AddEntry(tg_IN_LEFT,"IHWP In, Wien Left")
leg->AddEntry(tge_IN_LEFT,"IHWP In, Wien Left")
leg->AddEntry(tge_OUT_LEFT,"IHWP Out, Wien Left")
leg->AddEntry(tge_IN_Right,"IHWP In, Wien Right")
leg->AddEntry(tge_IN_RIGHT,"IHWP In, Wien Right")
leg->AddEntry(tge_OUT_RIGHT,"IHWP Out, Wien Right")
leg->Draw()
c1->SaveAs("withleg_maindet_asym.pdf")
.!pwd
