#!/bin/bash
root -l -b -q drawProf.C'(1,"Aq")'
root -l -b -q drawProf.C'(2,"Aq")'
root -l -b -q drawProf.C'(1,"BPM12X")' 
root -l -b -q drawProf.C'(2,"BPM12X")'
root -l -b -q drawProf.C'(1,"BPM1X")' 
root -l -b -q drawProf.C'(2,"BPM1X")'
root -l -b -q drawProf.C'(1,"BPM4eX")' 
root -l -b -q drawProf.C'(2,"BPM4eX")'
root -l -b -q drawProf.C'(1,"BPM4eY")' 
root -l -b -q drawProf.C'(2,"BPM4eY")'
root -l -b -q drawProf.C'(1,"raw_us_avg")' 
root -l -b -q drawProf.C'(2,"raw_us_avg")'
root -l -b -q drawProf.C'(1,"reg_us_avg")' 
root -l -b -q drawProf.C'(2,"reg_us_avg")'
