#!/bin/bash
root -l -b -q pullAq.C'(1,"respin2","Aq")'
root -l -b -q pullAq.C'(2,"respin2","Aq")'
root -l -b -q pullAq.C'(1,"respin2","BPM12X")' 
root -l -b -q pullAq.C'(2,"respin2","BPM12X")'
root -l -b -q pullAq.C'(1,"respin2","BPM1X")' 
root -l -b -q pullAq.C'(2,"respin2","BPM1X")'
root -l -b -q pullAq.C'(1,"respin2","BPM4eX")' 
root -l -b -q pullAq.C'(2,"respin2","BPM4eX")'
root -l -b -q pullAq.C'(1,"respin2","BPM4eY")' 
root -l -b -q pullAq.C'(2,"respin2","BPM4eY")'
root -l -b -q pullAq.C'(1,"respin2","raw_us_avg")' 
root -l -b -q pullAq.C'(2,"respin2","raw_us_avg")'
root -l -b -q pullAq.C'(1,"respin2","reg_us_avg")' 
root -l -b -q pullAq.C'(2,"respin2","reg_us_avg")'
