mul_trip->Draw("rcdb_sign*asym_bcm_an_us.hw_sum/1e-9:((ErrorFlag==0 && SinceLastTripEnd<3000)*SinceLastTripEnd)-((NonTripErrorFlag==0 && UntilNextTripEnd<1000)*UntilNextTripEnd)","((ErrorFlag==0 && SinceLastTripEnd<3000) || (UntilNextTripEnd<1000)) && rcdb_flip_state==1","prof")
mul_trip->Draw("rcdb_sign*asym_bcm_an_us.hw_sum/1e-9:((ErrorFlag==0 && SinceLastTripEnd<3000)*SinceLastTripEnd)-((NonTripErrorFlag==0 && UntilNextTripEnd<1000)*UntilNextTripEnd)","((ErrorFlag==0 && SinceLastTripEnd<300) || (UntilNextTripEnd<200)) && rcdb_flip_state==1","prof")
mul_trip->Draw("rcdb_sign*asym_bcm_an_us.hw_sum/1e-9:((ErrorFlag==0 && SinceLastTripEnd<300)*SinceLastTripEnd)-((NonTripErrorFlag==0 && UntilNextTripEnd<200)*UntilNextTripEnd)","((ErrorFlag==0 && SinceLastTripEnd<300) || (UntilNextTripEnd<200)) && rcdb_flip_state==1","prof")
mul_trip->Draw("rcdb_sign*asym_bcm_an_us.hw_sum/1e-9:((ErrorFlag==0 && SinceLastTripEnd<3000)*SinceLastTripEnd)-((NonTripErrorFlag==0 && UntilNextTripEnd<1000)*UntilNextTripEnd)","((ErrorFlag==0 && SinceLastTripEnd<300) || (UntilNextTripEnd<200)) && rcdb_flip_state==1","prof")
mul_trip->Draw("rcdb_sign*asym_bcm_an_us.hw_sum/1e-9:((ErrorFlag==0 && SinceLastTripEnd<3000)*SinceLastTripEnd)-((NonTripErrorFlag==0 && UntilNextTripEnd<1000)*UntilNextTripEnd)","((ErrorFlag==0 && SinceLastTripEnd<3000 && UntilNextTripEnd>1000) || (NonTripErrorFlag==0 && UntilNextTripEnd<1000 && SinceLastTripEnd>3000)) && rcdb_flip_state==1","prof")
mul_trip->Draw("rcdb_sign*asym_bcm_an_us.hw_sum/1e-9:((ErrorFlag==0 && SinceLastTripEnd<3000)*SinceLastTripEnd)-((NonTripErrorFlag==0 && UntilNextTripEnd<1000)*UntilNextTripEnd)","((ErrorFlag==0 && SinceLastTripEnd<300 && UntilNextTripEnd>200) || (NonTripErrorFlag==0 && UntilNextTripEnd<200 && SinceLastTripEnd>300)) && rcdb_flip_state==1","prof")
mul_trip->Draw("rcdb_sign*asym_bcm_an_us.hw_sum/1e-9:((ErrorFlag==0 && SinceLastTripEnd<300)*SinceLastTripEnd)-((NonTripErrorFlag==0 && UntilNextTripEnd<200)*UntilNextTripEnd)","((ErrorFlag==0 && SinceLastTripEnd<300 && UntilNextTripEnd>200) || (NonTripErrorFlag==0 && UntilNextTripEnd<200 && SinceLastTripEnd>300)) && rcdb_flip_state==1","prof")
mul_trip->Draw("rcdb_sign*asym_bcm_an_us.hw_sum/1e-9:((ErrorFlag==0 && SinceLastTripEnd<300 && UntilNextTripEnd>200)*SinceLastTripEnd)-((NonTripErrorFlag==0 && UntilNextTripEnd<200 && UntilNextTripEnd>300)*UntilNextTripEnd)","((ErrorFlag==0 && SinceLastTripEnd<300 && UntilNextTripEnd>200) || (NonTripErrorFlag==0 && UntilNextTripEnd<200 && SinceLastTripEnd>300)) && rcdb_flip_state==1","prof")
mul_trip->Draw("rcdb_sign*asym_bcm_an_us.hw_sum/1e-9:((ErrorFlag==0 && SinceLastTripEnd<300 && UntilNextTripEnd>200)*SinceLastTripEnd)-((NonTripErrorFlag==0 && UntilNextTripEnd<200 && SinceLastTripEnd>300)*UntilNextTripEnd)","((ErrorFlag==0 && SinceLastTripEnd<300 && UntilNextTripEnd>200) || (NonTripErrorFlag==0 && UntilNextTripEnd<200 && SinceLastTripEnd>300)) && rcdb_flip_state==1","prof")
mul_trip->Draw("rcdb_sign*asym_bcm_an_us.hw_sum/1e-9:SinceLastTripEnd","ErrorFlag==0 && SinceLastTripEnd<1000 && rcdb_flip_state==2 && rcdb_slug<150","prof")
mul_trip->Draw("rcdb_sign*asym_bcm_an_us.hw_sum/1e-9:((ErrorFlag==0 && SinceLastTripEnd<3000)*SinceLastTripEnd)-((NonTripErrorFlag==0 && UntilNextTripEnd<1000)*UntilNextTripEnd)","((ErrorFlag==0 && SinceLastTripEnd<3000 && UntilNextTripEnd>1000) || (NonTripErrorFlag==0 && UntilNextTripEnd<1000 && SinceLastTripEnd>3000)) && rcdb_flip_state==1","prof")


 mul_trip->Draw("rcdb_sign*asym_bcm_an_us.hw_sum/1e-9:run_number","ErrorFlag==0 && SinceLastTripEnd>=0 && SinceLastTripEnd<=250 && rcdb_flip_state==1 && rcdb_slug>109 & rcdb_slug<114","prof same")

